$('.open-popup').click(function(e){
    e.preventDefault();
    $('.popup-bg').fadeIn(600);
    $('html').addClass('noscroll');
});
$('.close-popup').click(function(){
    $('.popup-bg').fadeOut(600);
    $('html').removeClass('no-scroll');
});